---
abstract: 'A fairly simplistic debug statement handler'
author:
  - 'Buddy Burden'
build_requires:
  B::Deparse: 0.89
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.29
  Test::More: 0.88
  Test::Output: 0.16
  Test::Warn: 0.21
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Debuggit
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 2.00_01
